services:
  # Main ROS2 system (SLAM, navigation, etc.)
  ros2-main:
    build: .
    image: ros2-dev:humble
    container_name: ros2_main
    volumes:
      - ../:/workspace
    network_mode: "host"
    privileged: true
    command: bash -c "
      source /opt/ros/humble/setup.bash &&
      source /microros_ws/install/local_setup.sh &&
      
    environment: 
      - DISPLAY
      # Start your main ROS2 nodes here
      

  # Micro-ROS agent (only if you want it as a service)
  microros-agent:
    image: ros2-dev:humble
    container_name: microros_agent
    network_mode: "host"
    command: bash -c "
      source /opt/ros/humble/setup.bash &&
      source /microros_ws/install/local_setup.sh &&
      ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888"
    restart: unless-stopped