services:
  ros2-dev:
    build: .
    image: ros2-dev:humble
    container_name: ros2_dev
    volumes:
      - ../:/workspace
    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true

  esp32:
    image: ros2-dev:humble
    container_name: ros2_esp32
    volumes:
      - ../:/workspace
    working_dir: /workspace/esp32
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    tty: true
    stdin_open: true

  backend:
    image: ros2-dev:humble
    container_name: ros2_backend
    volumes:
      - ../:/workspace
    working_dir: /workspace/backend
    network_mode: "host"
    tty: true
    stdin_open: true